blogicum/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('posts/<int:id>/', views.post_detail, name='post_detail'),
    path(
        'category/<slug:category_slug>/',
        views.category_posts,
        name='category_posts'
    ),
]

blogicum/blogicum/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('pages/', include('pages.urls')),
]

blogicum/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'

urlpatterns = [
    path('about/', views.about, name='about'),
    path('rules/', views.rules, name='rules'),
]

blogicum/blog/models.py
# from django.db import models

# Create your models here.

blogicum/pages/models.py
# from django.db import models

# Create your models here.

blogicum/blog/views.py
from django.shortcuts import render

posts = [
    {
        'id': 0,
        'location': 'Остров отчаянья',
        'date': '30 сентября 1659 года',
        'category': 'travel',
        'text': '''Наш корабль, застигнутый в открытом море
                страшным штормом, потерпел крушение.
                Весь экипаж, кроме меня, утонул; я же,
                несчастный Робинзон Крузо, был выброшен
                полумёртвым на берег этого проклятого острова,
                который назвал островом Отчаяния.''',
    },
    {
        'id': 1,
        'location': 'Остров отчаянья',
        'date': '1 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Проснувшись поутру, я увидел, что наш корабль сняло
                с мели приливом и пригнало гораздо ближе к берегу.
                Это подало мне надежду, что, когда ветер стихнет,
                мне удастся добраться до корабля и запастись едой и
                другими необходимыми вещами. Я немного приободрился,
                хотя печаль о погибших товарищах не покидала меня.
                Мне всё думалось, что, останься мы на корабле, мы
                непременно спаслись бы. Теперь из его обломков мы могли бы
                построить баркас, на котором и выбрались бы из этого
                гиблого места.''',
    },
    {
        'id': 2,
        'location': 'Остров отчаянья',
        'date': '25 октября 1659 года',
        'category': 'not-my-day',
        'text': '''Всю ночь и весь день шёл дождь и дул сильный
                порывистый ветер. 25 октября.  Корабль за ночь разбило
                в щепки; на том месте, где он стоял, торчат какие-то
                жалкие обломки,  да и те видны только во время отлива.
                Весь этот день я хлопотал  около вещей: укрывал и
                укутывал их, чтобы не испортились от дождя.''',
    },
]


def index(request):
    reversed_posts = list(reversed(posts))
    context = {'posts': reversed_posts}
    return render(request, 'blog/index.html', context)


def post_detail(request, id):
    post = next((post for post in posts if post['id'] == id), None)
    return render(request, 'blog/detail.html', {'post': post})


def category_posts(request, category_slug):
    context = {'category_slug': category_slug}
    return render(request, 'blog/category.html', context)

blogicum/pages/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'pages/about.html')


def rules(request):
    return render(request, 'pages/rules.html')

blogicum/templates/blog/category.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Blogikum - Категория</title>
</head>
<body>
    <h1>Публикации в категории - {{ category_slug }}</h1>
</body>
</html>

blogicum/templates/blog/detail.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Blogikum - Пост</title>
</head>
<body>
    <h1>{{ post.location }}</h1>
    <p>{{ post.date }}</p>
    <p>{{ post.text }}</p>
    <a href="{% url 'blog:index' %}">Назад к списку</a>
</body>
</html>

blogicum/templates/blog/index.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Blogikum - Главная</title>
</head>
<body>
    <h1>Главная страница</h1>
    <ul>
        {% for post in posts %}
            <li>
                <strong>{{ post.location }}</strong> - {{ post.date }} - {{ post.category }}<br>
            </li>
            <p>{{ post.text|slice:":20" }}</p>
            <a href="{% url 'blog:post_detail' post.id %}">Читать подробнее</a>
        {% endfor %}
    </ul>
</body>
</html>

blogicum/templates/pages/about.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>About</title>
</head>
<body>
    <h1>О проекте</h1>
    <p>Это страница о проекте Blogikum.</p>
</body>
</html>

blogicum/templates/pages/rules.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Rules</title>
</head>
<body>
    <h1>Правила</h1>
    <p>Это страница с правилами проекта Blogikum.</p>
</body>
</html>